name: App1

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app1/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app1/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "manimullapudi" --password-stdin
        docker image build /home/runner/work/.github/app1/ -t manimullapudi/app1:dev 
        docker push manimullapudi/app1:dev
