name: App3

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app3/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app3/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "test" --password-stdin
        docker image build /home/runner/work/.github/app3/ -t manimullapudi/app3:dev 
        docker push manimullapudi/app3:dev
